### ISSUE TITLE
xstream series support

### ISSUE THREAD

**Issue by kodiaddict** [stereodruid/plugin.video.pseudo.library#1]
Hi stereodruid,

I've looked at your osmosi port before it was gone and really liked what I saw. Forking is definetely the better approach.

I've tried to add support for series added through the xstream plugins in the original PseudoLibrary code and it was actually pretty easy:

...
            if strm_type in ['TV','Episodes']:
                if url.find('plugin://plugin.video.xstream/')==0:
                    episode = re.search('"episode":(.*?),', f).group(1) 
                    season = re.search('"season":(.*?),', f).group(1) 
                    title = urllib.quote(re.search('"showtitle" *: *"(.*?)",', f).group(1).strip()).replace('/','-').replace('\\','-')
                    episode_title = urllib.quote(re.search('"title" *: *"(.*?)",', f).group(1).strip()).replace('/','-').replace('\\','-')
                    path = os.path.join('TV',title,'Season '+season)
                    filename = 'S'+season+'E'+episode+' '+episode_title
                else:                
                    path = os.path.join('TV',strm_name)
                    filename = strm_name + ' - ' + label
                print path, filename
..

This will create strm files in the form:

userdata\plugin.video.pseudo.library\strms\TV\Empire\Season 2\S2E1 Episode%201%20-%20Alle%20Teufel%20sind%20hier.strm

These can correctly be imported into the Kodi library for all series stream providers that are currently in xstream.

Since you had some other enhancements, like the update service (which seems to be gone from the original code?), I was wondering if you want to give my code a try. 

Having the update service again, would be nice.

As another comment: I didn't understand why you saw the need to add additonal categories apart from  TV, Epsiodes, Movies and Others, but maybe you can explain here.

Cheers!

**Comment by stereodruid** [comment]
@kodiaddict 
I didn’t gave up,  just decided to fork and then to implement my changes to PseudoLibrary.
Since the last push to OSMOSIS, I made many changes to the code and tried to make it smarter.

Thanks for your code, I will see if I can use it. I think my next attempt  will be to get the content type structure earlier in the code, so there will be less need to manipulate strings 

I added the category because I wanted my tv-shows in a separated folder called something different then ‘TV’.  In  my new version I added the category ‘TV-Shows’ and removed ‘Episodes Kinox’

I am not a developer so maybe the code will be a bit ugly, and I don’t know if Lunatixz will accept my code.
Anyway my next release will be very soon.

Regards.

**Comment by stereodruid** [comment]
Found a bug in you code i guess:
if strm_type in ['TV','Episodes']:
Yours
if url.find('plugin://plugin.video.xstream/')==0:

Should be:
if strm_type in ['TV','Episodes']:
if url.find('plugin://plugin.video.xstream/')== -1:

Otherwise it will  always enter the if. A negative retun of. find() is -1. Or?

**Comment by Lunatixz** [comment]
@kodiaddict PseudoLibrary was written to universal work with all plugins. I'm not sure forking in order to support one single plugin is wise. It benefits the greater community to continue the universal approach and correct any issues that are causing incompatibility with a specific plugin.

**Comment by kodiaddict** [comment]
@Lunatixz: I don't get your point. This is a fork from your code, not a clone. Once stereodroid has finished debugging his changes, he can start a pull request, so that the changes get back into your github repository.

**Comment by Lunatixz** [comment]
I'm speaking in regards to the clone project, which is now a proper fork... We must have cross communicated.

Yes, once I receive the additions @stereodruid  and I can bring the code up to date.

**Comment by Lunatixz** [comment]
What is xstreams BTW? If it's a illegal plugin? I would appreciate we not specifically address it then. Meaning code will be written to work with "ALL" kodi plugins, but I don't want plugin specific code. @kodiaddict regex can be added to work without the need for a plugin check.

**Comment by stereodruid** [comment]
#2
